test:
  image: jitesoft/composer:latest
  script:
    - composer install --prefer-source --no-interaction
    - vendor/bin/phpunit --configuration phpunit.xml --colors=never
    - vendor/bin/phpcs -p --report=summary --standard=style.xml src
